In [1]:
import pandas as pd
import numpy as np
from scipy import stats
import math

1. Провести дисперсионный анализ для определения того, есть ли различия среднего роста среди взрослых футболистов, хоккеистов и штангистов.
Даны значения роста в трех группах случайно выбранных спортсменов:
Футболисты: 173, 175, 180, 178, 177, 185, 183, 182.
Хоккеисты: 177, 179, 180, 188, 177, 172, 171, 184, 180.
Штангисты: 172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170.

In [2]:
y1 = np.array([173, 175, 180, 178, 177, 185, 183, 182])
y1

array([173, 175, 180, 178, 177, 185, 183, 182])

In [3]:
y2 = np.array([177, 179, 180, 188, 177, 172, 171, 184, 180])
y2

array([177, 179, 180, 188, 177, 172, 171, 184, 180])

In [4]:
y3 = np.array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])
y3

array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])

In [5]:
y1_av=y1.mean()
y1_av

179.125

In [6]:
y2_av=y2.mean()
y2_av

178.66666666666666

In [7]:
y3_av=y3.mean()
y3_av

172.72727272727272

In [8]:
k=3

In [9]:
n1=len(y1)
n1

8

In [10]:
n2=len(y2)
n2

9

In [11]:
n3=len(y3)
n3

11

In [12]:
Y_av=(sum(y1)+sum(y2)+sum(y3))/(n1+n2+n3)
Y_av

176.46428571428572

In [13]:
S_2_1=0
i=1
for i in range(n1):
    S_2_1=S_2_1+(y1[i]-Y_av)**2
S_2_1

175.5102040816323

In [14]:
S_2_2=0
i=1
for i in range(n2):
    S_2_2=S_2_2+(y2[i]-Y_av)**2
S_2_2

271.6543367346936

In [15]:
S_2_3=0
i=1
for i in range(n3):
    S_2_3=S_2_3+(y3[i]-Y_av)**2
S_2_3

383.7997448979599

In [16]:
S_2 = S_2_1 + S_2_2 + S_2_3
S_2

830.9642857142858

In [17]:
S_p2=(y1_av-Y_av)**2*n1+(y2_av-Y_av)**2*n2+(y3_av-Y_av)**2*n3
S_p2

253.9074675324678

In [18]:
S_2_ost_1=0
i=1
for i in range(n1):
    S_2_ost_1=S_2_ost_1+(y1[i]-y1_av)**2
S_2_ost_1

118.875

In [19]:
S_2_ost_2=0
i=1
for i in range(n2):
    S_2_ost_2=S_2_ost_2+(y2[i]-y2_av)**2
S_2_ost_2

227.99999999999997

In [20]:
S_2_ost_3=0
i=1
for i in range(n3):
    S_2_ost_3=S_2_ost_3+(y3[i]-y3_av)**2
S_2_ost_3

230.18181818181816

In [21]:
S_2_ost = S_2_ost_1 + S_2_ost_2 + S_2_ost_3
S_2_ost

577.0568181818181

In [22]:
sigma_p2 = S_p2/(k-1)
sigma_p2

126.9537337662339

In [23]:
sigma_2_ost = S_2_ost/(n1+n2+n3-k)
sigma_2_ost

23.082272727272724

In [24]:
F= sigma_p2/sigma_2_ost
F

5.500053450812599

In [25]:
stats.f_oneway(y1,y2,y3)

F_onewayResult(statistic=5.500053450812596, pvalue=0.010482206918698694)

In [26]:
df_межд = k-1
df_межд

2

In [27]:
df_внутр = n1+n2+n3-k
df_внутр 

25

In [28]:
alpha = 0.01

In [29]:
F_крит = 2.53

In [30]:
5.5 > 2.53

True

Следовательно , раздичие между группами статистически значимое при alpha = 0.01

In [31]:
alpha = 0.05

In [32]:
F_крит = 3.38

In [33]:
5.5>3.35

True

Следовательно , раздичие между группами статистически значимое при alpha = 0.05

2. Прикрепить ссылку на курсовой проект на github. (см. выбор темы в ДЗ к Уроку 6)

In [ ]:
РАБОТА БУДЕТ ВЫЛОЖЕНА  ПО ЭТОЙ ЖЕ ССЫЛКЕ в течении недели.